<?php
/**
 * Created by PhpStorm.
 * User: Vae
 * Date: 2020/7/23
 * Time: 16:01
 */

namespace app\controller;


use think\Controller;
use think\facade\Env;

class Index extends Controller
{
    protected  function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo '测试一下';
    }

    public function  index()
 {
     return '准备下班了'.\think\facade\Env::get('app_path');
 }
    public function  arr()
    {
        $data=array('a'=>1 ,'b'=>2 , 'c'=>3 );
        return json($data);
    }

    public function  Abc()
    {
        return view();
    }
}